### ISSUE TITLE
Deciding on the tech stack

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#1]
I am considering MEAN for most of the system. Perhaps not Mongo, but some kind of a SQL DB.

In order to satisfy the requirement of having at least two different languages at the backend, I propose Python, and C/C++ as our team members have experience with these langauges.

**Comment by tilaks26** [comment]
This is a Quora discussion I found comparing MySQL and PostgreSQL.

[Link](https://www.quora.com/What-are-pros-and-cons-of-PostgreSQL-and-MySQL?share=1)

**Comment by amolrbhagwat** [comment]
Shouldn't the second language be the one in which the prediction logic is implemented in?

**Comment by tilaks26** [comment]
@marpierc , could we go ahead and use Javascript for UI (angular js) and some of the micro services (node js)? By doing so, will we still need two other languages for the remaining micro services?

**Comment by smarru** [comment]
Yes you will need three different languages ..node and angular are two different frameworks for a single language

**Comment by tilaks26** [comment]
Thank you, @smarru
