### ISSUE TITLE
Framework to build APIs

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/TeamAviato#2]
We must discuss the framework needed to build APIs. As of now, we have considered Apache Thrift and REST. In my opinion, we can go ahead with Thrift because it generates both the client and server interfaces and the client calls will be more consistent. Also, Thrift supports various protocols and languages.

**Comment by amolrbhagwat** [comment]
I think Thrift should be the way to go. Neither Simple Binary Encoding, nor Google Protocol Buffers support JS. There are forks which support JS, but we'd rather stick to a technology backed by an organization/company rather than an individual.

**Comment by tilaks26** [comment]
This is a good doc I found for Thrift.
[Apache Thrift](https://diwakergupta.github.io/thrift-missing-guide/)

**Comment by tilaks26** [comment]
Another one - [Thrift](http://anoori.me/blog/programming/thriftpart-one-introduction/)

**Comment by amolrbhagwat** [comment]
We decided on using REST for communication.
