### ISSUE TITLE
Ideas on how to proceed with branching for the second milestone.

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#27]

**Comment by LaxmiBhavaniM** [comment]
As of now we just have separate feature branches. We haven't had a development branch yet. How about merging our features from Milestone 1 onto development branch and continue working on our individual branches?

**Comment by tilaks26** [comment]
Yeah. Sounds good. But we won't be able to successfully build the development branch cause of the clash in .travis.yml files.

**Comment by amolrbhagwat** [comment]
@gouravshenoy @vaglomangirish kindly share your thoughts.

**Comment by vaglomangirish** [comment]
There are 3 options from what I see:-

1) You could have dev branches created for every micro service, wherein you merge the milestone 1 code and build on top of it, without touching the milestone 1 branches. Once you finish milestone 2, take a new milestone 2 branch for every microservice.

2) Continue developing from the current branches and create a new fork for milestone 2, like you created for milestone 1 for submission

3) Ideal way would be (had discussed this with other AIs and @marpierc Marlon, @smarru Suresh), create your own git organization (e.g. airavata-courses is an organization) and separate repos for every micro service under your organization. Each microservice repo would have master, dev and deliverable branches created.

You may choose whichever option works the best for you, just make sure you don't lose the milestone 1 checkpoint and during your submission you have the deliverable repo and instructions clear.

Hope this helps.

**Comment by amolrbhagwat** [comment]
@vaglomangirish What is your opinion on having a milestone branch for each microservice? We merge our current branches to their milestone branches for each milestone, and continue development on the current branches. (It's kind of like method 1 which you mentioned)

**Comment by gouravshenoy** [comment]
@amolrbhagwat , In my opinion creating a separate organization (analogy: similar to 'Airavata-Courses') would be a good choice, and then maintaining different repositories under the organization for different micro-services (analogy: similar to 'Team-Aviato', 'Team-Apex', etc). And then within each repository (for that micro-service), have master, dev & milestone-x release branches.

But again, if that does not seem feasible for your team then you can have separate 'dev' branches for each micro-service under the current setup. You could create 'dev-<microservice>' branch for working on developments (eg: dev-api-gateway). And when you feel that it is ready for a milestone release, you can merge respective 'dev-<micro-service>' branch with the '<micro-service>' branch.

Hope this helps!

**Comment by gouravshenoy** [comment]
@amolrbhagwat , In my opinion creating a separate organization (analogy: similar to 'Airavata-Courses') would be a good choice, and then maintaining different repositories under the organization for different micro-services (analogy: similar to 'Team-Aviato', 'Team-Apex', etc). And then within each repository (for that micro-service), have master, dev & milestone-x release branches.

But again, if that does not seem feasible for your team then you can have separate 'dev' branches for each micro-service under the current setup. You could create 'dev-<microservice>' branch for working on developments (eg: dev-api-gateway). And when you feel that it is ready for a milestone release, you can merge respective 'dev-<micro-service>' branch with the '<micro-service>' branch.

Hope this helps!

**Comment by amolrbhagwat** [comment]
We have decided to go ahead with a parallel branch for each branch, called <microservice>-releases, wherein for each milestone, we would merge our current branch onto it, and have a corresponding commit message.

**Comment by gouravshenoy** [comment]
@amolrbhagwat Sounds good! You plan on creating -dev branches for working on development, or continue developing in existing feature branches?

**Comment by amolrbhagwat** [comment]
@gouravshenoy We plan on continuing development on the current branches. Creating a -dev branch for each microservice would create unnecessary clutter.
