### ISSUE TITLE
New thread per microservice per request - is it necessary for the gateway as well?

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#28]
The gateway has been implemented in Node. From what I understand, there's only only thread, and the entire program runs a single event loop. And that is what makes Node so scalable.

@marpierc @smarru So I assume there's no need to make this microservice spawn a new thread. Is that correct?

**Comment by marpierc** [comment]
For gateways generally, the Web front end should not be the bottleneck.  I was more interested in the microservice scaling.

Marlon
