### ISSUE TITLE
Add login

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#4]

**Comment by amolrbhagwat** [comment]
@smarru @marpierc I am thinking of cloning and building upon https://github.com/tk26/Mentorly for the user login and authentication. Is that fine? If I clone the repo, would that be considered as plagiarism?

**Comment by smarru** [comment]
Yes its fine. No, it will not be plagiarism as long as you clearly acknowledge in your README and a NOTICE file what you are using.

Suresh
