### ISSUE TITLE
Delegator failing, with Docker error "unregister_netdevice: waiting for lo to become free. Usage count = 1"

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#43]
This seems to be a known bug in Docker, and all the discussions mention this to be in fact, a kernel bug. Upgrading the kernel didn't help.

**Comment by amolrbhagwat** [comment]
Spoke to @vaglomangirish regarding this issue. He said that Docker is known to have networking problems. He suggested trying to increase the processor and memory if possible. He also advised us to take a look at Singularity.

**Comment by amolrbhagwat** [comment]
All of the following mention this to be a kernel issue:
1. https://github.com/docker/docker/issues/5618
2. https://github.com/coreos/bugs/issues/254
3. https://www.bountysource.com/issues/2004254-unregister_netdevice-waiting-for-lo-to-become-free-usage-count-3

This question also seems to be an issue while running Xen, further indicating this issue to be originating in the kernel:
1. http://serverfault.com/questions/650377/linux-kernel-bug-w-netns-and-or-xen-guest-unregister-netdevice-waiting-for

**Comment by tilaks26** [comment]
@marpierc @smarru Please take a look at this. Thank you.

**Comment by marpierc** [comment]
Please add the course TAs.

**Comment by amolrbhagwat** [comment]
@vaglomangirish @gouravshenoy @ajinkya-dhamnaskar @abhijitkaranjkar89
