### ISSUE TITLE
Format for requesting info about a station

### ISSUE THREAD

**Issue by amolrbhagwat** [airavata-courses/TeamAviato#5]
@tilaks26 Would a JSON in this format do?
{
  "station" : "ABCD",
  "date" : "YYYY-MM-DD",
  "time" : "HHMMSS"
}

**Comment by tilaks26** [comment]
Yeah, this will do.

**Comment by amolrbhagwat** [comment]
The format changes after a certain date. Check: https://aws.amazon.com/noaa-big-data/nexrad/

**Comment by amolrbhagwat** [comment]
Just a list of station names and locations: http://apollo.lsc.vsc.edu/classes/remote/lecture_notes/radar/88d/88D_locations.html

**Comment by amolrbhagwat** [comment]
This format was finalized with two additional fields: userName, and requestId.
